### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by XiaoyuLiu198** [KungPaoChick/Find_LinkedIn_jobs#2]
Hi Matt. Your project seems quite interesting, well done! But how did you solve the problem of automatic logging in, I didn't see the part in the code, however in your demo seems everything worked well. I tried requests+beaultiful soup before, however, it's hard to get pass the login part. I also tried your package, no result was returned.

**Comment by Kungger-git** [comment]
Hello.. There was never any login text box appearing, and I just thought it was a good thing... Though I have abandoned this project, because ipinfo.io doesn't work in my region anymore. Sorry for the inconvenience. :<
